	DE1_SoC_QSYS u0 (
		.vid_clk_to_the_alt_vip_cti_0                (<connected-to-vid_clk_to_the_alt_vip_cti_0>),                //          alt_vip_cti_0_clocked_video.vid_clk
		.vid_data_to_the_alt_vip_cti_0               (<connected-to-vid_data_to_the_alt_vip_cti_0>),               //                                     .vid_data
		.overflow_from_the_alt_vip_cti_0             (<connected-to-overflow_from_the_alt_vip_cti_0>),             //                                     .overflow
		.vid_datavalid_to_the_alt_vip_cti_0          (<connected-to-vid_datavalid_to_the_alt_vip_cti_0>),          //                                     .vid_datavalid
		.vid_locked_to_the_alt_vip_cti_0             (<connected-to-vid_locked_to_the_alt_vip_cti_0>),             //                                     .vid_locked
		.alt_vip_itc_0_clocked_video_vid_clk         (<connected-to-alt_vip_itc_0_clocked_video_vid_clk>),         //          alt_vip_itc_0_clocked_video.vid_clk
		.alt_vip_itc_0_clocked_video_vid_data        (<connected-to-alt_vip_itc_0_clocked_video_vid_data>),        //                                     .vid_data
		.alt_vip_itc_0_clocked_video_underflow       (<connected-to-alt_vip_itc_0_clocked_video_underflow>),       //                                     .underflow
		.alt_vip_itc_0_clocked_video_vid_datavalid   (<connected-to-alt_vip_itc_0_clocked_video_vid_datavalid>),   //                                     .vid_datavalid
		.alt_vip_itc_0_clocked_video_vid_v_sync      (<connected-to-alt_vip_itc_0_clocked_video_vid_v_sync>),      //                                     .vid_v_sync
		.alt_vip_itc_0_clocked_video_vid_h_sync      (<connected-to-alt_vip_itc_0_clocked_video_vid_h_sync>),      //                                     .vid_h_sync
		.alt_vip_itc_0_clocked_video_vid_f           (<connected-to-alt_vip_itc_0_clocked_video_vid_f>),           //                                     .vid_f
		.alt_vip_itc_0_clocked_video_vid_h           (<connected-to-alt_vip_itc_0_clocked_video_vid_h>),           //                                     .vid_h
		.alt_vip_itc_0_clocked_video_vid_v           (<connected-to-alt_vip_itc_0_clocked_video_vid_v>),           //                                     .vid_v
		.clk_50                                      (<connected-to-clk_50>),                                      //                        clk_50_clk_in.clk
		.reset_n                                     (<connected-to-reset_n>),                                     //                  clk_50_clk_in_reset.reset_n
		.clk_sdram_clk                               (<connected-to-clk_sdram_clk>),                               //                            clk_sdram.clk
		.clk_vga_clk                                 (<connected-to-clk_vga_clk>),                                 //                              clk_vga.clk
		.fifo_0_out_valid                            (<connected-to-fifo_0_out_valid>),                            //                           fifo_0_out.valid
		.fifo_0_out_data                             (<connected-to-fifo_0_out_data>),                             //                                     .data
		.fifo_0_out_ready                            (<connected-to-fifo_0_out_ready>),                            //                                     .ready
		.hps_0_h2f_reset_reset_n_reset_n             (<connected-to-hps_0_h2f_reset_reset_n_reset_n>),             //              hps_0_h2f_reset_reset_n.reset_n
		.hps_io_hps_io_emac1_inst_TX_CLK             (<connected-to-hps_io_hps_io_emac1_inst_TX_CLK>),             //                               hps_io.hps_io_emac1_inst_TX_CLK
		.hps_io_hps_io_emac1_inst_TXD0               (<connected-to-hps_io_hps_io_emac1_inst_TXD0>),               //                                     .hps_io_emac1_inst_TXD0
		.hps_io_hps_io_emac1_inst_TXD1               (<connected-to-hps_io_hps_io_emac1_inst_TXD1>),               //                                     .hps_io_emac1_inst_TXD1
		.hps_io_hps_io_emac1_inst_TXD2               (<connected-to-hps_io_hps_io_emac1_inst_TXD2>),               //                                     .hps_io_emac1_inst_TXD2
		.hps_io_hps_io_emac1_inst_TXD3               (<connected-to-hps_io_hps_io_emac1_inst_TXD3>),               //                                     .hps_io_emac1_inst_TXD3
		.hps_io_hps_io_emac1_inst_RXD0               (<connected-to-hps_io_hps_io_emac1_inst_RXD0>),               //                                     .hps_io_emac1_inst_RXD0
		.hps_io_hps_io_emac1_inst_MDIO               (<connected-to-hps_io_hps_io_emac1_inst_MDIO>),               //                                     .hps_io_emac1_inst_MDIO
		.hps_io_hps_io_emac1_inst_MDC                (<connected-to-hps_io_hps_io_emac1_inst_MDC>),                //                                     .hps_io_emac1_inst_MDC
		.hps_io_hps_io_emac1_inst_RX_CTL             (<connected-to-hps_io_hps_io_emac1_inst_RX_CTL>),             //                                     .hps_io_emac1_inst_RX_CTL
		.hps_io_hps_io_emac1_inst_TX_CTL             (<connected-to-hps_io_hps_io_emac1_inst_TX_CTL>),             //                                     .hps_io_emac1_inst_TX_CTL
		.hps_io_hps_io_emac1_inst_RX_CLK             (<connected-to-hps_io_hps_io_emac1_inst_RX_CLK>),             //                                     .hps_io_emac1_inst_RX_CLK
		.hps_io_hps_io_emac1_inst_RXD1               (<connected-to-hps_io_hps_io_emac1_inst_RXD1>),               //                                     .hps_io_emac1_inst_RXD1
		.hps_io_hps_io_emac1_inst_RXD2               (<connected-to-hps_io_hps_io_emac1_inst_RXD2>),               //                                     .hps_io_emac1_inst_RXD2
		.hps_io_hps_io_emac1_inst_RXD3               (<connected-to-hps_io_hps_io_emac1_inst_RXD3>),               //                                     .hps_io_emac1_inst_RXD3
		.hps_io_hps_io_qspi_inst_IO0                 (<connected-to-hps_io_hps_io_qspi_inst_IO0>),                 //                                     .hps_io_qspi_inst_IO0
		.hps_io_hps_io_qspi_inst_IO1                 (<connected-to-hps_io_hps_io_qspi_inst_IO1>),                 //                                     .hps_io_qspi_inst_IO1
		.hps_io_hps_io_qspi_inst_IO2                 (<connected-to-hps_io_hps_io_qspi_inst_IO2>),                 //                                     .hps_io_qspi_inst_IO2
		.hps_io_hps_io_qspi_inst_IO3                 (<connected-to-hps_io_hps_io_qspi_inst_IO3>),                 //                                     .hps_io_qspi_inst_IO3
		.hps_io_hps_io_qspi_inst_SS0                 (<connected-to-hps_io_hps_io_qspi_inst_SS0>),                 //                                     .hps_io_qspi_inst_SS0
		.hps_io_hps_io_qspi_inst_CLK                 (<connected-to-hps_io_hps_io_qspi_inst_CLK>),                 //                                     .hps_io_qspi_inst_CLK
		.hps_io_hps_io_sdio_inst_CMD                 (<connected-to-hps_io_hps_io_sdio_inst_CMD>),                 //                                     .hps_io_sdio_inst_CMD
		.hps_io_hps_io_sdio_inst_D0                  (<connected-to-hps_io_hps_io_sdio_inst_D0>),                  //                                     .hps_io_sdio_inst_D0
		.hps_io_hps_io_sdio_inst_D1                  (<connected-to-hps_io_hps_io_sdio_inst_D1>),                  //                                     .hps_io_sdio_inst_D1
		.hps_io_hps_io_sdio_inst_CLK                 (<connected-to-hps_io_hps_io_sdio_inst_CLK>),                 //                                     .hps_io_sdio_inst_CLK
		.hps_io_hps_io_sdio_inst_D2                  (<connected-to-hps_io_hps_io_sdio_inst_D2>),                  //                                     .hps_io_sdio_inst_D2
		.hps_io_hps_io_sdio_inst_D3                  (<connected-to-hps_io_hps_io_sdio_inst_D3>),                  //                                     .hps_io_sdio_inst_D3
		.hps_io_hps_io_usb1_inst_D0                  (<connected-to-hps_io_hps_io_usb1_inst_D0>),                  //                                     .hps_io_usb1_inst_D0
		.hps_io_hps_io_usb1_inst_D1                  (<connected-to-hps_io_hps_io_usb1_inst_D1>),                  //                                     .hps_io_usb1_inst_D1
		.hps_io_hps_io_usb1_inst_D2                  (<connected-to-hps_io_hps_io_usb1_inst_D2>),                  //                                     .hps_io_usb1_inst_D2
		.hps_io_hps_io_usb1_inst_D3                  (<connected-to-hps_io_hps_io_usb1_inst_D3>),                  //                                     .hps_io_usb1_inst_D3
		.hps_io_hps_io_usb1_inst_D4                  (<connected-to-hps_io_hps_io_usb1_inst_D4>),                  //                                     .hps_io_usb1_inst_D4
		.hps_io_hps_io_usb1_inst_D5                  (<connected-to-hps_io_hps_io_usb1_inst_D5>),                  //                                     .hps_io_usb1_inst_D5
		.hps_io_hps_io_usb1_inst_D6                  (<connected-to-hps_io_hps_io_usb1_inst_D6>),                  //                                     .hps_io_usb1_inst_D6
		.hps_io_hps_io_usb1_inst_D7                  (<connected-to-hps_io_hps_io_usb1_inst_D7>),                  //                                     .hps_io_usb1_inst_D7
		.hps_io_hps_io_usb1_inst_CLK                 (<connected-to-hps_io_hps_io_usb1_inst_CLK>),                 //                                     .hps_io_usb1_inst_CLK
		.hps_io_hps_io_usb1_inst_STP                 (<connected-to-hps_io_hps_io_usb1_inst_STP>),                 //                                     .hps_io_usb1_inst_STP
		.hps_io_hps_io_usb1_inst_DIR                 (<connected-to-hps_io_hps_io_usb1_inst_DIR>),                 //                                     .hps_io_usb1_inst_DIR
		.hps_io_hps_io_usb1_inst_NXT                 (<connected-to-hps_io_hps_io_usb1_inst_NXT>),                 //                                     .hps_io_usb1_inst_NXT
		.hps_io_hps_io_spim1_inst_CLK                (<connected-to-hps_io_hps_io_spim1_inst_CLK>),                //                                     .hps_io_spim1_inst_CLK
		.hps_io_hps_io_spim1_inst_MOSI               (<connected-to-hps_io_hps_io_spim1_inst_MOSI>),               //                                     .hps_io_spim1_inst_MOSI
		.hps_io_hps_io_spim1_inst_MISO               (<connected-to-hps_io_hps_io_spim1_inst_MISO>),               //                                     .hps_io_spim1_inst_MISO
		.hps_io_hps_io_spim1_inst_SS0                (<connected-to-hps_io_hps_io_spim1_inst_SS0>),                //                                     .hps_io_spim1_inst_SS0
		.hps_io_hps_io_uart0_inst_RX                 (<connected-to-hps_io_hps_io_uart0_inst_RX>),                 //                                     .hps_io_uart0_inst_RX
		.hps_io_hps_io_uart0_inst_TX                 (<connected-to-hps_io_hps_io_uart0_inst_TX>),                 //                                     .hps_io_uart0_inst_TX
		.hps_io_hps_io_i2c0_inst_SDA                 (<connected-to-hps_io_hps_io_i2c0_inst_SDA>),                 //                                     .hps_io_i2c0_inst_SDA
		.hps_io_hps_io_i2c0_inst_SCL                 (<connected-to-hps_io_hps_io_i2c0_inst_SCL>),                 //                                     .hps_io_i2c0_inst_SCL
		.hps_io_hps_io_i2c1_inst_SDA                 (<connected-to-hps_io_hps_io_i2c1_inst_SDA>),                 //                                     .hps_io_i2c1_inst_SDA
		.hps_io_hps_io_i2c1_inst_SCL                 (<connected-to-hps_io_hps_io_i2c1_inst_SCL>),                 //                                     .hps_io_i2c1_inst_SCL
		.hps_io_hps_io_gpio_inst_GPIO09              (<connected-to-hps_io_hps_io_gpio_inst_GPIO09>),              //                                     .hps_io_gpio_inst_GPIO09
		.hps_io_hps_io_gpio_inst_GPIO35              (<connected-to-hps_io_hps_io_gpio_inst_GPIO35>),              //                                     .hps_io_gpio_inst_GPIO35
		.hps_io_hps_io_gpio_inst_GPIO40              (<connected-to-hps_io_hps_io_gpio_inst_GPIO40>),              //                                     .hps_io_gpio_inst_GPIO40
		.hps_io_hps_io_gpio_inst_GPIO41              (<connected-to-hps_io_hps_io_gpio_inst_GPIO41>),              //                                     .hps_io_gpio_inst_GPIO41
		.hps_io_hps_io_gpio_inst_GPIO48              (<connected-to-hps_io_hps_io_gpio_inst_GPIO48>),              //                                     .hps_io_gpio_inst_GPIO48
		.hps_io_hps_io_gpio_inst_GPIO53              (<connected-to-hps_io_hps_io_gpio_inst_GPIO53>),              //                                     .hps_io_gpio_inst_GPIO53
		.hps_io_hps_io_gpio_inst_GPIO54              (<connected-to-hps_io_hps_io_gpio_inst_GPIO54>),              //                                     .hps_io_gpio_inst_GPIO54
		.hps_io_hps_io_gpio_inst_GPIO61              (<connected-to-hps_io_hps_io_gpio_inst_GPIO61>),              //                                     .hps_io_gpio_inst_GPIO61
		.i2c_data_0_external_connection_export       (<connected-to-i2c_data_0_external_connection_export>),       //       i2c_data_0_external_connection.export
		.i2c_end_flag_0_external_connection_export   (<connected-to-i2c_end_flag_0_external_connection_export>),   //   i2c_end_flag_0_external_connection.export
		.out_port_from_the_i2c_scl                   (<connected-to-out_port_from_the_i2c_scl>),                   //          i2c_scl_external_connection.export
		.bidir_port_to_and_from_the_i2c_sda          (<connected-to-bidir_port_to_and_from_the_i2c_sda>),          //          i2c_sda_external_connection.export
		.i2c_start_flag_0_external_connection_export (<connected-to-i2c_start_flag_0_external_connection_export>), // i2c_start_flag_0_external_connection.export
		.key_external_connection_export              (<connected-to-key_external_connection_export>),              //              key_external_connection.export
		.ledr_external_connection_export             (<connected-to-ledr_external_connection_export>),             //             ledr_external_connection.export
		.memory_mem_a                                (<connected-to-memory_mem_a>),                                //                               memory.mem_a
		.memory_mem_ba                               (<connected-to-memory_mem_ba>),                               //                                     .mem_ba
		.memory_mem_ck                               (<connected-to-memory_mem_ck>),                               //                                     .mem_ck
		.memory_mem_ck_n                             (<connected-to-memory_mem_ck_n>),                             //                                     .mem_ck_n
		.memory_mem_cke                              (<connected-to-memory_mem_cke>),                              //                                     .mem_cke
		.memory_mem_cs_n                             (<connected-to-memory_mem_cs_n>),                             //                                     .mem_cs_n
		.memory_mem_ras_n                            (<connected-to-memory_mem_ras_n>),                            //                                     .mem_ras_n
		.memory_mem_cas_n                            (<connected-to-memory_mem_cas_n>),                            //                                     .mem_cas_n
		.memory_mem_we_n                             (<connected-to-memory_mem_we_n>),                             //                                     .mem_we_n
		.memory_mem_reset_n                          (<connected-to-memory_mem_reset_n>),                          //                                     .mem_reset_n
		.memory_mem_dq                               (<connected-to-memory_mem_dq>),                               //                                     .mem_dq
		.memory_mem_dqs                              (<connected-to-memory_mem_dqs>),                              //                                     .mem_dqs
		.memory_mem_dqs_n                            (<connected-to-memory_mem_dqs_n>),                            //                                     .mem_dqs_n
		.memory_mem_odt                              (<connected-to-memory_mem_odt>),                              //                                     .mem_odt
		.memory_mem_dm                               (<connected-to-memory_mem_dm>),                               //                                     .mem_dm
		.memory_oct_rzqin                            (<connected-to-memory_oct_rzqin>),                            //                                     .oct_rzqin
		.pll_0_locked_export                         (<connected-to-pll_0_locked_export>),                         //                         pll_0_locked.export
		.pll_audio_locked_export                     (<connected-to-pll_audio_locked_export>),                     //                     pll_audio_locked.export
		.zs_addr_from_the_sdram                      (<connected-to-zs_addr_from_the_sdram>),                      //                           sdram_wire.addr
		.zs_ba_from_the_sdram                        (<connected-to-zs_ba_from_the_sdram>),                        //                                     .ba
		.zs_cas_n_from_the_sdram                     (<connected-to-zs_cas_n_from_the_sdram>),                     //                                     .cas_n
		.zs_cke_from_the_sdram                       (<connected-to-zs_cke_from_the_sdram>),                       //                                     .cke
		.zs_cs_n_from_the_sdram                      (<connected-to-zs_cs_n_from_the_sdram>),                      //                                     .cs_n
		.zs_dq_to_and_from_the_sdram                 (<connected-to-zs_dq_to_and_from_the_sdram>),                 //                                     .dq
		.zs_dqm_from_the_sdram                       (<connected-to-zs_dqm_from_the_sdram>),                       //                                     .dqm
		.zs_ras_n_from_the_sdram                     (<connected-to-zs_ras_n_from_the_sdram>),                     //                                     .ras_n
		.zs_we_n_from_the_sdram                      (<connected-to-zs_we_n_from_the_sdram>),                      //                                     .we_n
		.spi_0_external_MISO                         (<connected-to-spi_0_external_MISO>),                         //                       spi_0_external.MISO
		.spi_0_external_MOSI                         (<connected-to-spi_0_external_MOSI>),                         //                                     .MOSI
		.spi_0_external_SCLK                         (<connected-to-spi_0_external_SCLK>),                         //                                     .SCLK
		.spi_0_external_SS_n                         (<connected-to-spi_0_external_SS_n>),                         //                                     .SS_n
		.sw_external_connection_export               (<connected-to-sw_external_connection_export>),               //               sw_external_connection.export
		.out_port_from_the_td_reset_n                (<connected-to-out_port_from_the_td_reset_n>),                //       td_reset_n_external_connection.export
		.in_port_to_the_td_status                    (<connected-to-in_port_to_the_td_status>),                    //        td_status_external_connection.export
		.uart_external_connection_rxd                (<connected-to-uart_external_connection_rxd>),                //             uart_external_connection.rxd
		.uart_external_connection_txd                (<connected-to-uart_external_connection_txd>),                //                                     .txd
		.play_out_0_external_connection_export       (<connected-to-play_out_0_external_connection_export>)        //       play_out_0_external_connection.export
	);

